name: Use the Composite Action with Actions

on:
  push:
    branches: [ "main" ]

jobs:
  myJob:
    name: My Job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

#      - name: Pull and run Docker image
#        run: |
#            docker pull mcr.microsoft.com/mssql/server:2019-latest
#            docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Phu@123456789" --name sql-server-2019-container  -p 1435:1433 -d mcr.microsoft.com/mssql/server:2019-latest
#            docker ps
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sewnguyenp2206
          password: Phu0005l5


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: sewnguyenp2206/api-gateway
